biblio/biblio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include('books.urls')),
    path("admin/", admin.site.urls),
]

biblio/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add, name='add'),
    path('addrec/', views.addrec, name='addrec'),
    # path('update/', views.update, name='update'),
    # path('books/', views.books_list, name='book_list'),
    # path('profile/', views.profile_edit, name='profile_edit')
]

biblio/books/models.py
from django.db import models


class Book(models.Model):
    name = models.CharField('Наименование', max_length=20)
    title = models.CharField('Заголовок', null=True, max_length=30)
    author = models.CharField('Автор', max_length=30)
    description = models.CharField('Описание', null=True, max_length=512)
    price = models.IntegerField('Цена', max_length=5)

biblio/books/views.py
from django.shortcuts import render, redirect
from .models import Book


def index(request):
    title = 'Head page'
    template = 'books/index.html'
    book = Book.objects.all()
    context = {
        'title': title,
        'text': 'Text page',
        'book': book
    }
    return render(request, template, context=context)


def add(request):
    template = 'books/add.html'
    return render(request, template)


def addrec(request):
    a = request.POST['name']
    b = request.POST['title']
    c = request.POST['author']
    d = request.POST['description']
    e = request.POST['price']
    book = Book(name=a, title=b, author=c, description=d, price=e)
    book.save()
    return redirect('/')


def books_list(request):
    pass


def profile_edit(request):
    pass

biblio/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en" class="h-100">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <title>Sticky Footer Navbar Template · Bootstrap v4.6</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body class="d-flex flex-column h-100">
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main role="main" class="flex-shrink-0">
      <div class="container">
        <h1 class="mt-5">Head</h1>
        <p class="lead">
          {% block content %}{{ text }}{% endblock %}
        </p>
      </div>
    </main>
    <footer class="footer mt-auto py-3">
      {% include 'includes/footer.html' %}
    </footer>
    <script src="{% static 'js/jquery.slim.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  </body>
</html>

biblio/templates/books/add.html
{% extends 'base.html' %}
{% block content %}

    <div class="row">
        <div class="col-12 col-sm-12 col-md-3">
            <h1>Добавление книги</h1>
            <form action="{% url 'books:addrec' %}" method="post">
                {% csrf_token %}
                <label for="">Наименование</label>
                <br>
                <br>
                <input type="text" name="name">
                <br>
                <br>
                <label for="">Заголовок</label>
                <br>
                <br>
                <input type="text" name="title">
                <br>
                <br>
                <label for="">Автор</label>
                <br>
                <br>
                <input type="text" name="author">
                <br>
                <br>
                <label for="">Описание</label>
                <br>
                <br>
                <input type="text" name="description">
                <br>
                <br>
                <label for="">Цена</label>
                <br>
                <br>
                <input type="text" name="price">
                <br>
                <br>
                <button type="submit" id="new">Применить</button>
            </form>
        </div>
    </div>

{% endblock %}

biblio/templates/books/index.html
{% extends 'base.html' %}
{% block content %}

<div class="row">
    <div class="col-12 col-sm-12 col-md-3">
        <h1>Members</h1>
        <table id="customers" border="1">
            <thead>
                <th>Id</th>
                <th>Наименование</th>
                <th>Заголовок</th>
                <th>Автор</th>
                <th>Описание</th>
                <th>Цена</th>
                <th colspan="2" id="mid">Action</th>
            </thead>
            {% for x in book %}
                <tr>
                    <td>{{ x.id }}</td>
                    <td>{{ x.name }}</td>
                    <td>{{ x.title }}</td>
                    <td>{{ x.author }}</td>
                    <td>{{ x.description }}</td>
                    <td>{{ x.price }}</td>
                    <td>
                        <a href="">
                            <button id='up'>Редактировать</button>
                        </a>
                    </td>
                    <td>
                        <a href="">
                            <button id='del'>Удалить</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <br><br>
        <a href="{% url 'books:add' %}"><button id="new3">Добавить книгу</button></a>
    </div>
</div>

{% endblock %}

biblio/templates/books/update.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-12 col-sm-12 col-md-3">
            <h1>Редактировать книгу</h1>
            <form action="">
                <label for="">Наименование</label>
                <br>
                <br>
                <input type="text">
                <br>
                <br>
                <label for="">Заголовок</label>
                <br>
                <br>
                <input type="text">
                <br>
                <br>
                <label for="">Автор</label>
                <br>
                <br>
                <input type="text">
                <br>
                <br>
                <label for="">Описание</label>
                <br>
                <br>
                <input type="text">
                <br>
                <br>
                <label for="">Цена</label>
                <br>
                <br>
                <input type="text">
                <br>
                <br>
                <button type="submit" id="new">Применить</button>
            </form>
        </div>
    </div>

{% endblock %}

biblio/templates/includes/footer.html
<div class="container">
    <span class="text-muted">2024</span>
</div>

biblio/templates/includes/header.html
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Biblio</a>
    <button class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarCollapse"
            aria-controls="navbarCollapse"
            aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Books <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Profile</a>
            </li>
        </ul>
    </div>
</nav>